### ISSUE TITLE
script does not have -f option

### ISSUE THREAD

**Issue by mkuzak** [c-martinez/sc-shell#1]
my `script` says
`usage: script [-adkpqr] [-t time] [file [command ...]]`
it does not accept `-f` option
I'm on OS X El Capitan, unfortunately `script` does not have the option to print out its version, so I don't know what version it is.

**Comment by c-martinez** [comment]
Damn it mac!

`-f, --flush             run flush after each write`

Do you know how often mac writes to file? If often enough, we can drop the -f...

**Comment by mkuzak** [comment]
isn't it -t option?

**Comment by mkuzak** [comment]
by the way have you checked if it works on windows? is there `script` on windows?

**Comment by c-martinez** [comment]
No, `-t`:

`-t, --timing[=<file>]   output timing data to stderr (or to FILE)`

which means it adds timestamps to the output, I think.

Not sure it works on windows (haven't tested) -- but I think git bash does

**Comment by mkuzak** [comment]
hm, in my `man pages` it says:
-t time
             Specify the interval at which the script output file will be
             flushed to disk, in seconds.  A value of 0 causes script to flush
             after every character I/O event.  The default interval is 30 sec-
             onds.

**Comment by c-martinez** [comment]
ah, then it is -t in mac... grrr... We need to add an if mac do this, if linux do that, if windows the other..

**Comment by c-martinez** [comment]
I think [this](https://stackoverflow.com/questions/1854/python-what-os-am-i-running-on) should solve our problem.

@mkuzak - can you confirm you get `darwin` ?

**Comment by mkuzak** [comment]
I do get `darwin`

**Comment by c-martinez** [comment]
good stuff...

**Comment by c-martinez** [comment]
@mkuzak -- try again. 2b71e10 adds check for os. Still will need to see how it works on windows.

**Comment by c-martinez** [comment]
Tried on windows, `script` does not exist (not even in git bash!). So windows will not be supported at the moment. Tough luck for windows users, but I think we'll need a windows expert to find a solution there.

**Comment by mkuzak** [comment]
actually this is not that bad, this is the trainer who will use it, so higher chance he'll be on Linux or Mac

**Comment by c-martinez** [comment]
Exactly, that's why I'm not too worried about this.
