### ISSUE TITLE
use argument parsing library

### ISSUE THREAD

**Issue by mkuzak** [c-martinez/sc-shell#2]
I think it's better to use python argument parsing library like `argparse` instead of doing it by hand. That way you will also avoid printing help and usage information by hand and reduce the duplication of the code.

**Comment by c-martinez** [comment]
It's using docopt, not parsing by hand.

**Comment by mkuzak** [comment]
so you generate args from docstring :) ok, now I get it

**Comment by c-martinez** [comment]
Yup -- personal preference, but I think docopt is nicer than argparse. ;-)
